import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Main from "@/components/Main";
import "./extra.css"
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className={'relative'}>
          <NavBar/>
          {children}
          <Main/>
          <Footer/>
      </div>
      </body>
    </html>
  );
}
